# Generated by Django 4.0.6 on 2023-10-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
