# Generated by Django 4.0.6 on 2023-10-08 12:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=user.models.get_username, max_length=50, unique=True),
        ),
    ]
